/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import prospective.Port;
import prospective.Program;
import prospective.Workflow;
import retrospective.Execution;
import retrospective.User;
import retrospective.WExecution;
import retrospective.relationship.HadPlan;
import retrospective.relationship.Used;
import retrospective.relationship.WasAssociatedWith;
import retrospective.relationship.WasGeneratedBy;
import retrospective.relationship.WasInformedBy;
import retrospective.relationship.WasPartOf;
import java.io.File;
import prospective.relationship.HasDefaultParam;
import prospective.relationship.HasSubProgram;
import prospective.relationship.HasInPort;
import prospective.relationship.HasOutPort;
import retrospective.relationship.HadInPort;
import retrospective.relationship.HadOutPort;
import retrospective.relationship.WasDerivedFrom;
import utils.FileManager;
import utils.RDFManager;

/**
 *
 * @author Wellington
 */
public class JfrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JfrmPrincipal
     */
    public JfrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtProspPath = new javax.swing.JTextField();
        btnPropPath = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtxtRetroPath = new javax.swing.JTextField();
        btnRetroPath = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jtxtPath = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jrbtNewFile = new javax.swing.JRadioButton();
        jrbtExistingFile = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jtxtDataSetName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxtDataSetId = new javax.swing.JTextField();
        jbtnLoadFolder = new javax.swing.JButton();
        jbtnGenerate = new javax.swing.JButton();
        jbtnClose = new javax.swing.JButton();
        jlblTimeSpent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Taverna Cartridge");

        jLabel2.setText("Prospective Provenance Path");

        btnPropPath.setText("...");
        btnPropPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropPathActionPerformed(evt);
            }
        });

        jLabel3.setText("Retrospective Provenance Path");

        jtxtRetroPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtRetroPathActionPerformed(evt);
            }
        });

        btnRetroPath.setText("...");
        btnRetroPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetroPathActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtProspPath, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jtxtRetroPath, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRetroPath, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPropPath, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 250, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtProspPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPropPath))
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtRetroPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetroPath))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Source", jPanel1);

        jLabel7.setText("Path");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(jrbtNewFile);
        jrbtNewFile.setSelected(true);
        jrbtNewFile.setText("New File");
        jrbtNewFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtNewFileActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbtExistingFile);
        jrbtExistingFile.setText("Existing File");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbtNewFile)
                .addGap(32, 32, 32)
                .addComponent(jrbtExistingFile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbtExistingFile)
                    .addComponent(jrbtNewFile))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setText("Dataset");

        jtxtDataSetName.setText("Taverna");
        jtxtDataSetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDataSetNameActionPerformed(evt);
            }
        });

        jLabel9.setText("Dataset Id");

        jtxtDataSetId.setText("4");

        jbtnLoadFolder.setText("...");
        jbtnLoadFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoadFolderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jtxtDataSetId))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtxtDataSetName, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnLoadFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtDataSetId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtDataSetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnLoadFolder)
                    .addComponent(jtxtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        jTabbedPane2.addTab("Destination", jPanel2);

        jbtnGenerate.setText("Generate");
        jbtnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGenerateActionPerformed(evt);
            }
        });

        jbtnClose.setText("Close");
        jbtnClose.setMaximumSize(new java.awt.Dimension(85, 25));
        jbtnClose.setMinimumSize(new java.awt.Dimension(85, 25));
        jbtnClose.setPreferredSize(new java.awt.Dimension(85, 25));
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });

        jlblTimeSpent.setBackground(new java.awt.Color(0, 102, 204));
        jlblTimeSpent.setText("Time Spent");
        jlblTimeSpent.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(), javax.swing.BorderFactory.createCompoundBorder()));
        jlblTimeSpent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jbtnGenerate)
                .addGap(18, 18, 18)
                .addComponent(jbtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblTimeSpent, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnGenerate)
                    .addComponent(jbtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTimeSpent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("Source");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGenerateActionPerformed
        long beginTime = 0, endTime = 0;   
        float timeSpent = 0.0f;
        beginTime = System.currentTimeMillis();          
        generateFacts();            
        endTime = System.currentTimeMillis();                       
        timeSpent = endTime - beginTime;
        jlblTimeSpent.setText(Float.toString(timeSpent/1000));
        JOptionPane.showMessageDialog(null, "File generated successfully!");
    }//GEN-LAST:event_jbtnGenerateActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnCloseActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void jbtnLoadFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoadFolderActionPerformed
        JFileChooser file = new JFileChooser("C:\\Users\\Wellington\\Drive\\PhD\\Workflows\\Phylogenetic\\Phylo-Taverna\\provenance"); 
          file.setFileSelectionMode(JFileChooser.FILES_ONLY);
          int i= file.showSaveDialog(null);
        if (i==1){
            jtxtPath.setText("");
        } else {
            File  archive = file.getSelectedFile();
           jtxtPath.setText(archive.getPath());
        }
    }//GEN-LAST:event_jbtnLoadFolderActionPerformed

    private void btnPropPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropPathActionPerformed
        JFileChooser file = new JFileChooser("C:\\Users\\Wellington\\Drive\\PhD\\Workflows\\Phylogenetic\\Phylo-Taverna\\provenance"); 
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i = file.showSaveDialog(null);
        if (i == 1){
            jtxtProspPath.setText("");
        } else {
            File  archive = file.getSelectedFile();
           jtxtProspPath.setText(archive.getPath());
        }
    }//GEN-LAST:event_btnPropPathActionPerformed

    private void jtxtDataSetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDataSetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDataSetNameActionPerformed

    private void btnRetroPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetroPathActionPerformed
        JFileChooser file = new JFileChooser("C:\\Users\\Wellington\\Drive\\PhD\\Workflows\\Phylogenetic\\Phylo-Taverna\\provenance"); 
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i = file.showSaveDialog(null);
        if (i == 1){
            jtxtRetroPath.setText("");
        } else {
            File  archive = file.getSelectedFile();
           jtxtRetroPath.setText(archive.getPath());
        }
    }//GEN-LAST:event_btnRetroPathActionPerformed

    private void jrbtNewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtNewFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtNewFileActionPerformed

    private void jtxtRetroPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtRetroPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtRetroPathActionPerformed
     /**
     * @param args the command line arguments
     */
    public static void main(String [] args){
        JfrmPrincipal jfrmPrincipal = new JfrmPrincipal();
        jfrmPrincipal.setVisible(true);    
        jfrmPrincipal.setLocationRelativeTo(null);
        jfrmPrincipal.setTitle("Integrated Provenance  Analysis");
        jfrmPrincipal.jrbtNewFile.setSelected(true);        
    }
    
    public void generateFacts(){ 
        
        //Salvar conexao em arquivo texto com delimitador ou xml
        //Gerar automaticamente o id do dataset() (precisa ler o arquivo de fatos prolog)        
    
        StringBuffer output;
        FileWriter writer;  
        
        String discontigous =   ":- discontiguous(dataSet/2).\n" +
                                ":- discontiguous(hasDataSet/2).\n" +
                                ":- discontiguous(hadDataSet/2).\n" +
                                ":- discontiguous(entity/2).\n" +
                                ":- discontiguous(activity/2).\n" +
                                ":- discontiguous(agent/2).\n" +
                                ":- discontiguous(hasInPort/2).\n" +
                                ":- discontiguous(hasOutPort/2).\n" +
                                ":- discontiguous(hadInPort/2).\n" +
                                ":- discontiguous(hadOutPort/2).\n" +
                                ":- discontiguous(hasDefaultParam/2).\n" +
                                ":- discontiguous(hasSubProgram/2).\n" +
                                ":- discontiguous(hadPlan/2).\n" +
                                ":- discontiguous(used/2).\n" +
                                ":- discontiguous(wasPartOf/2).\n" +
                                ":- discontiguous(wasGeneratedBy/2).\n" +
                                ":- discontiguous(wasInformedBy/2).\n" +
                                ":- discontiguous(wasPartOf/2).\n" +
                                ":- discontiguous(wasAssociatedWith/2).\n";
                
        String dataSetId = jtxtDataSetId.getText();
        String dataSetName = jtxtDataSetName.getText();
        String file = jtxtPath.getText();
        if(!file.substring(file.length()-3).equals(".pl"))
            file += ".pl";
                  
        output = new StringBuffer();
    
        if(jrbtNewFile.isSelected())
            output.append(discontigous);
        else
            output.append("\n");
        
        output.append("dataSet(");
        output.append(dataSetId);
        output.append(",'");
        output.append(dataSetName);
        output.append("').\n");

        //Retrospective Provenance
        RDFManager rdf = new RDFManager(jtxtRetroPath.getText());//"C:\\Users\\Well\\Dropbox\\Workspace\\Taverna2Facts\\Provenance4\\workflowrun.prov.ttl");        
           
        new Execution(output, rdf);
        new WExecution(output, dataSetId, rdf);
        new retrospective.Data(output, rdf);
        new WasGeneratedBy(output, rdf);
        new Used(output, rdf);
        new WasInformedBy(output, rdf);
        new WasPartOf(output, rdf);
        new WasAssociatedWith(output, rdf); 
        new HadPlan(output, rdf);
        new HadInPort(output, rdf);
        new HadOutPort(output, rdf);
        new WasDerivedFrom(output, rdf); 
        new Port(output, rdf); //Prospective, beccause there is a error in the wfdesc file (input ports are also classified as output port)               
        new HasDefaultParam(output, rdf);//Prospective, because there is no data id in rdf2
        new User(output, rdf);
        
        //Prospective Provenance
        RDFManager rdf2 = new RDFManager(jtxtProspPath.getText());//"C:\\Users\\Well\\Dropbox\\Workspace\\Taverna2Facts\\Provenance4\\.ro\\annotations\\workflow.wfdesc.ttl"); 
        
        new Workflow(output, dataSetId, rdf2);
        new Program(output, rdf2);
        new HasSubProgram(output, rdf2);         
        new HasInPort(output, rdf2);
        new HasOutPort(output, rdf2); 
        
        
        
        try {
            FileManager fileManager = new FileManager();
            if(jrbtExistingFile.isSelected())
                writer = fileManager.getWriter(file, true); //path, append (true) or new file (false)  
            else
                writer = fileManager.getWriter(file, false); //path, append (true) or new file (false)  
            writer.write(output.substring(0, output.length()-1));
            writer.close();             
        } catch(IOException e) {
            e.printStackTrace();
        }         
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPropPath;
    private javax.swing.JButton btnRetroPath;
    public javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton jbtnClose;
    private javax.swing.JButton jbtnGenerate;
    private javax.swing.JButton jbtnLoadFolder;
    private javax.swing.JLabel jlblTimeSpent;
    private javax.swing.JRadioButton jrbtExistingFile;
    private javax.swing.JRadioButton jrbtNewFile;
    private javax.swing.JTextField jtxtDataSetId;
    private javax.swing.JTextField jtxtDataSetName;
    private javax.swing.JTextField jtxtPath;
    private javax.swing.JTextField jtxtProspPath;
    private javax.swing.JTextField jtxtRetroPath;
    // End of variables declaration//GEN-END:variables
}
