/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uff.ic.view;

import br.uff.ic.io.Extractor;
import br.uff.ic.ws.DomainDataCapturer;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Wellington
 */
public class JfrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JfrmExtractor
     */
    public JfrmPrincipal() {    
        initComponents();
        jcbxWebService.setModel(new DefaultComboBoxModel(new String[] {"EBI ENA", "NCBI", "GenBank"}));
    }

    public static void main(String args[]) {
        JfrmPrincipal jfrmPrincipal = new JfrmPrincipal();
        jfrmPrincipal.setVisible(true);
        jfrmPrincipal.setLocationRelativeTo(null);
        jfrmPrincipal.setTitle("Domain Data");
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtPath = new javax.swing.JTextField();
        jbtnInputPath = new javax.swing.JButton();
        jbtnExtract = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtxtWkfExecution = new javax.swing.JTextField();
        jcbxWebService = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtOutputPath = new javax.swing.JTextField();
        jbtnOutputPath = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtxtPosition = new javax.swing.JTextField();
        jlblTimeSpent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Fasta Input Path");

        jtxtPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPathActionPerformed(evt);
            }
        });

        jbtnInputPath.setText("...");
        jbtnInputPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInputPathActionPerformed(evt);
            }
        });

        jbtnExtract.setText("Execute");
        jbtnExtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExtractActionPerformed(evt);
            }
        });

        jLabel2.setText("Workflow Execution");

        jtxtWkfExecution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtWkfExecutionActionPerformed(evt);
            }
        });

        jcbxWebService.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Web Service");

        jLabel4.setText("Prolog Output Path");

        jbtnOutputPath.setText("...");
        jbtnOutputPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOutputPathActionPerformed(evt);
            }
        });

        jLabel5.setText("Obj_Id Column Position");
        jLabel5.setEnabled(false);

        jtxtPosition.setText("1");
        jtxtPosition.setEnabled(false);
        jtxtPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPositionActionPerformed(evt);
            }
        });

        jlblTimeSpent.setText("Time Spent");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbxWebService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtPosition)))
                    .addComponent(jtxtWkfExecution))
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtOutputPath, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnInputPath, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnOutputPath, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(24, 24, 24))))
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jbtnExtract)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblTimeSpent)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtWkfExecution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbxWebService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnInputPath))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtOutputPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnOutputPath))
                        .addGap(18, 18, 18)
                        .addComponent(jbtnExtract))
                    .addComponent(jlblTimeSpent))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnInputPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInputPathActionPerformed
        jtxtPath.setText(fileChoose());
    }//GEN-LAST:event_jbtnInputPathActionPerformed

    private String fileChoose(){
        JFileChooser file = new JFileChooser(); 
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i = file.showSaveDialog(null);
        if (i == 1){
            //jtxtPath.setText("");
            return "";
        } else {
            File  archive = file.getSelectedFile();
           //jtxtPath.setText(archive.getPath());
           return archive.getPath();
        }    
    }
    
    private void jbtnExtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExtractActionPerformed
        long beginTime = 0, endTime = 0;   
        float timeSpent = 0.0f;
        beginTime = System.currentTimeMillis();  
        
        Extractor extractor = new Extractor();
        ArrayList<String> objIdList = extractor.extractObjId(jtxtPath.getText(),Integer.parseInt(jtxtPosition.getText()));
        DomainDataCapturer capturer = new DomainDataCapturer();    
        capturer.executeWSClient(jcbxWebService.getSelectedIndex(), objIdList, jtxtOutputPath.getText(), jtxtWkfExecution.getText());
        
        endTime = System.currentTimeMillis();                       
        timeSpent = endTime - beginTime;
        jlblTimeSpent.setText(Float.toString(timeSpent/1000));
        JOptionPane.showMessageDialog(null, "Successfully generated facts from external sources!");        
        

    }//GEN-LAST:event_jbtnExtractActionPerformed

    private void jbtnOutputPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOutputPathActionPerformed
        jtxtOutputPath.setText(fileChoose());
    }//GEN-LAST:event_jbtnOutputPathActionPerformed

    private void jtxtPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPathActionPerformed

    private void jtxtPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPositionActionPerformed

    private void jtxtWkfExecutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtWkfExecutionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtWkfExecutionActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtnExtract;
    private javax.swing.JButton jbtnInputPath;
    private javax.swing.JButton jbtnOutputPath;
    private javax.swing.JComboBox<String> jcbxWebService;
    private javax.swing.JLabel jlblTimeSpent;
    private javax.swing.JTextField jtxtOutputPath;
    private javax.swing.JTextField jtxtPath;
    private javax.swing.JTextField jtxtPosition;
    private javax.swing.JTextField jtxtWkfExecution;
    // End of variables declaration//GEN-END:variables
}
