/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package control.retrospective.relationship;

import DAO.QueryDB;
import java.sql.ResultSet;
import java.sql.SQLException;
import model.Prov;

/**
 *
 * @author nwm26
 */
public class WasGeneratedBy {
    String data, execution, sql;   
    ResultSet rs, rs2;
    QueryDB queryDAO;  
    
    public WasGeneratedBy(StringBuffer output, String database2){
        //get all fields of all relations (ports)
        sql =   "Select f.fieldid, r.relid, r.wkfid, ewkfid, r.rname, r.rtype, fname\n" +
                "from crelation r, cfield f, eworkflow ew, cworkflow w\n" +
                "where r.relid = f.relid\n" +
                "and r.wkfid = w.wkfid\n" +
                "and ew.tag = w.tag\n" +
                "order by ewkfid, f.fieldid";                  
        queryDAO = new QueryDB();                    
        rs = queryDAO.getTable(sql);
                
        try {
            while(rs.next()) {
                //if a output field/value was generated by another execution (previoustaskid)
                if(rs.getString("rtype").equals("INTERMEDIARY")){
                    sql =   "SELECT ewkfid, previoustaskid, " + rs.getString("fname") + 
                            " from " +  database2 + "." + rs.getString("rname") +
                            " where ewkfid = " + rs.getString("ewkfid") + 
                            " group by ewkfid, previoustaskid, " + rs.getString("fname"); //a same previoustaskid can have more than one nexttaskid
                    rs2 = queryDAO.getTable(sql); 
                    while(rs2.next()){
                        execution = "ex" + rs2.getString("previoustaskid");
                        data = "d" + rs.getString("fieldid") + rs.getString("ewkfid");                
                        generateFact(output);    
                        
                        //if lat execution - need change because it can has more than one field
                        if(rs.isLast() && rs2.isLast()){
                            execution = "ew" + rs2.getString("ewkfid");
                            data = "d" + rs.getString("fieldid") + rs.getString("ewkfid");                
                            generateFact(output); 
                        }                        
                        
                    }                      
                //if a output field/value was generated by another execution (taskid)
                }else if(rs.getString("rtype").equals("OUTPUT")){
                    sql =   "SELECT ewkfid, taskid, " + rs.getString("fname") + 
                            " from " +  database2 + "." + rs.getString("rname") +
                            " where ewkfid = " + rs.getString("ewkfid") + 
                            " order by ewkfid, taskid"; 
                    rs2 = queryDAO.getTable(sql); 
                    while(rs2.next()){
                        execution = "ex" + rs2.getString("taskid");
                        data = "d" + rs.getString("fieldid") + rs.getString("ewkfid");                
                        generateFact(output);  
                        
                        //if last execution - need change because it can has more than one field
                        if(rs.isLast() && rs2.isLast()){
                            execution = "ew" + rs2.getString("ewkfid");
                            data = "d" + rs.getString("fieldid") + rs.getString("ewkfid");                
                            generateFact(output); 
                        }                           
                    }                     
                }                   
            }    
            rs.close();
            rs2.close();              
        } catch(SQLException e) {
            e.printStackTrace();
        } 
        wasGeneratedByDoc(output);                                             
    }  
    
    public void wasGeneratedByDoc(StringBuffer output){
        //if a output document was generated by another execution (taskid)
        sql = "SELECT f.fileid, f.taskid, f.fname, f.fieldname " +
              "FROM efile f " + 
              "WHERE f.fname != 'EErr.txt' and f.fname != 'ERelation.txt' and f.fname != 'EResult.txt' " +
              "and f.fname != 'experiment.cmd' and f.fname != 'extractor.cmd' and f.fname != 'experiment.cmd~'  and f.fname != 'extractor.cmd~'";
              
        queryDAO = new QueryDB();                    
        rs = queryDAO.getTable(sql);
        try {
            while(rs.next()) {              
                data = "dc" + rs.getString("fileid");
                execution = "ex" + rs.getString("taskid");                
                generateFact(output);
            }
        } catch(SQLException e) {
            e.printStackTrace();
        }           
    }
    
    public void generateFact(StringBuffer output){                 
        output.append(Prov.WASGENERATEDBY);
        output.append("(");        
        output.append(data);
        output.append("s");
        output.append(",");
        output.append(execution);
        output.append("s");
        output.append(").\n");                   
    }
}
